name: CI
on:
  push:
    branches:
      - issue#31
jobs:
  ci:
    name: Integration & CodeQL Analysis & Slack WebHook & SonarCloud Scan
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run-script build-prod  # package.json -> "scripts"

      - name: Run Tests & Generate Coverage
        run: npm run test-ci

      - name: Initialize CodeQL
        if: success()
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript-typescript'
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"

      - name: Slack WebHook
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,author,commit,author,workflow,
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@v2 # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPOS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
