name: CD
on:
  push:
    branches:
      - main
jobs:
  cd:
    name: Build & Deploy on S3
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_S3 }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run-script build-prod

      - name: Deploy
        if: success()
        run: aws s3 sync dist/tfm-web/browser s3://tfm-web-s3 --delete
